### PR TITLE
GitHub Action to lint Python code

### PR DESCRIPTION
**Pull request by cclauss**
Test results: https://github.com/cclauss/yours-daily/actions

### CODE REVIEW

**Comment by tuminzee** [comment]
> Test results: https://github.com/cclauss/yours-daily/actions

Thank you for the PR.
I have never tried adding actions. I'd like to learn more about it.

This will go in my to-do list.

**Comment by tuminzee** [comment]
Do you mind if I take some time to study this, I will merge it asap.

**Comment by cclauss** [comment]
Take your time...  No rush at all.

**Comment by tuminzee** [comment]
This is great. Thank you so much for contributing here. 
I am sure, I will learn a lot during this process.

**Comment by tuminzee** [comment]
> Take your time... No rush at all.

Linting is good. I will try to add this in my practise.
Thank you so much for this.

I will also setup this locally so that I can monitor these errors, before pushing it.

Read about it from the below links
https://realpython.com/python-code-quality/
https://pylint.pycqa.org/en/latest/intro.html
https://github.com/cclauss/GitHub-Action-for-pylint

**Comment by cclauss** [comment]
I prefer flake8 over pylint but to each his own.

**Comment by tuminzee** [comment]
to me both are new. So I will try both of them. 
Thank you again for contributing here. I will make sure that it passes all the tests soon

**Pull request merged**
